version: "3.0"

services:
  caddy:
    container_name: caddy
    image: caddy:2.4.5-alpine
    restart: unless-stopped
    pull_policy: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy:/data
      - ./data/caddy/config:/config
    networks:
      - caddy_network

networks:
  caddy_network:
    name: caddy_network
