version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    # ports:
    #   - 8096:8096
    volumes:
      - ./data/jellyfin/config:/config
      - ./data/tvshows:/data/tvshows
      - ./data/movies:/data/movies
      - jellyfin_cache:/cache
    restart: 'unless-stopped'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
      - JELLYFIN_PublishedServerUrl=https://night.haolieu-skyblieu.net
    networks:
      - caddy_network

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - ./data/sonarr/config:/config
      - ./data/tvshows:/tv #optional
      - ./data/sonarr/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - caddy_network

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - ./data/radarr/config:/config
      - ./data/movies:/movies #optional
      - ./data/radarr/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - caddy_network

volumes:
  jellyfin_cache:

networks:
  caddy_network:
    name: caddy_network
    external: true
