version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    # ports:
    #   - 8096:8096
    volumes:
      - ./data/jellyfin/config:/config
      - ./data/jellyfin/media:/media
      - ./data/jellyfin/media2:/media2:ro
      - ./data/jellyfin/tvshows:/data/tvshows
      - ./data/jellyfin/movies:/data/movies
      - jellyfin_cache:/cache
    restart: 'unless-stopped'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
      - JELLYFIN_PublishedServerUrl=https://night.haolieu-skyblieu.net
    networks:
      - caddy_network

volumes:
  jellyfin_cache:

networks:
  caddy_network:
    name: caddy_network
    external: true
