version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    # ports:
    #   - 8096:8096
    volumes:
      - ./data/jellyfin/config:/config
      - ./config.json:/jellyfin/jellyfin-web/config.json
      - ./data/tvshows:/data/tvshows
      - ./data/movies:/data/movies
      - jellyfin_cache:/cache
    restart: 'unless-stopped'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
      - JELLYFIN_PublishedServerUrl=https://night.haolieu-skyblieu.net
    networks:
      - caddy_network

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - ./data/sonarr/config:/config
      - ./data/tvshows:/tv #optional
      - ./data/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - caddy_network

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - ./data/radarr/config:/config
      - ./data/movies:/movies #optional
      - ./data/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - caddy_network

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - ./data/jackett/config:/config
      - ./data/radarr/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    networks:
      - caddy_network

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
      - WEBUI_PORT=8080
    volumes:
      - ./data/qbittorent/config:/config
      - ./data/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      - caddy_network

  ombi:
    image: lscr.io/linuxserver/ombi:latest
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - ./data/ombi/config:/config
    # ports:
    #   - 3579:3579
    restart: unless-stopped
    networks:
      - caddy_network

volumes:
  jellyfin_cache:

networks:
  caddy_network:
    name: caddy_network
    external: true
