version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: uid:gid
    network_mode: 'host'
    # ports:
    #   - 8096:8096
    volumes:
      - ./data/jellyfin/config:/config
      - ./data/jellyfin/media:/media
      - ./data/jellyfin/media2:/media2:ro
      - jellyfin_cache:/cache
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
      - JELLYFIN_PublishedServerUrl=https://night.haolieu-blieusky.net
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - caddy_network

volumes:
  jellyfin_cache:

networks:
  caddy_network:
    name: caddy_network
    external: true