version: "3"

services:
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    hostname: rabbitmq
    # ports:
    #   - "5672:5672"
    #   - "15672:15672"
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    env_file:
      - rabbitmq.env
    environment:
      - RABBITMQ_DEFAULT_USER=blieu
    networks:
      - caddy_network

networks:
  caddy_network:
    external: true
