version: "3.0"
services:
  ddclient:
    image: ghcr.io/linuxserver/ddclient
    container_name: ddclient
    pull_policy: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - ./ddclient.conf:/config/ddclient.conf
    restart: unless-stopped